### ISSUE TITLE
Why you don't publish it to the flow-typed repo?

### ISSUE THREAD

**Issue by retyui** [SatsumaLabs/react-native-typed-navigation#1]
Repo https://github.com/flow-typed/flow-typed/
And [CONTRIBUTING](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md)

**Comment by retyui** [comment]
@george-steel :1st_place_medal:

**Comment by george-steel** [comment]
The flow-typed repository is only for pure type definitions which correspond exactly to the code in a library. As this wrapper contains additional code (see the README section regarding `registerComponent` for an explanation as to why) it does not meet the criteria of flow-typed and should instead be published to npm.
